---
abstract: 'Human readable date periods'
author:
  - 'Peter Stuifzand <peter@stuifzand.eu>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Period-Human
provides:
  Date::Period::Human:
    file: lib/Date/Period/Human.pm
    version: v0.4.2
requires:
  Date::Calc: 0
  DateTime::Format::MySQL: 0
  Test::More: 0
  Test::Exception: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.4.2
